[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/=lib/chainlink/contracts/src/v0.8/"
]

[rpc_endpoints]
devnet = "https://devnet.dplabs-internal.com"
